import { useStudioStore } from "../../state/studioStore";
import { applyTheme } from "../../state/studioStore.shared";
import { buildMacWorkspacePreview, buildWindowsRightRailPreview, readPreviewScenario } from "./previewData";
import { DEFAULT_AUTO_RETRY_COUNT } from "../../../../../shared/kernel/requestModel.js";

export { readPreviewScenario } from "./previewData";

export function applyMacWorkspacePreviewToStore(workspaceId = "preview-workspace") {
  const preview = buildMacWorkspacePreview(workspaceId);
  applyTheme("dark");
  document.documentElement.style.setProperty("--font-scale", "1");

  useStudioStore.setState({
    apiKey: "sk-preview",
    mode: "edit",
    prompt: preview.currentImage.prompt,
    negativePrompt: preview.currentImage.negativePrompt ?? "",
    size: preview.currentImage.size,
    quality: preview.currentImage.quality,
    outputFormat: "png",
    seed: preview.currentImage.seed ?? 3200,
    background: preview.currentImage.background ?? "auto",
    outputCompression: preview.currentImage.outputCompression ?? 100,
    inputFidelity: preview.currentImage.inputFidelity ?? "auto",
    imageStyle: preview.currentImage.imageStyle ?? "default",
    moderation: preview.currentImage.moderation ?? "low",
    userIdentifier: "",
    partialImages: 1,
    autoRetryEnabled: true,
    autoRetryCount: DEFAULT_AUTO_RETRY_COUNT,
    kernelRuntimeMode: "auto",
    baseURL: preview.profile.baseURL,
    textModelID: preview.profile.textModelID,
    imageModelID: preview.profile.imageModelID,
    reasoningEffort: preview.profile.reasoningEffort,
    apiMode: preview.profile.apiMode,
    requestPolicy: preview.profile.requestPolicy,
    noPromptRevision: true,
    profiles: [preview.profile],
    activeProfileId: preview.profile.id,
    sources: preview.sources,
    runningJobs: [],
    jobsTotal: 0,
    jobsCompleted: 0,
    progress: null,
    streamPreview: null,
    streamPreviews: {},
    lastLogLine: "",
    errorMessage: null,
    errorRawPath: null,
    isRunning: false,
    lastPayload: null,
    runningJobMeta: {},
    currentImage: preview.currentImage,
    history: preview.history,
    batchResults: [],
    resultGridOpen: false,
    historyRailCollapsed: false,
    historyTimelineOpen: false,
    tool: "pan",
    brushSize: 24,
    brushMode: "paint",
    annotationKind: "rect",
    annotationColor: "#ff4d4d",
    selectedAnnotationId: null,
    maskDataURL: null,
    strokes: [],
    annotations: [],
    compareB: null,
    compareSplit: 0.5,
    toasts: [],
    recentDurations: preview.history.map((item) => item.elapsedSec ?? 0).filter((value) => value > 0),
    viewZoom: 1,
    canvasViewResetTick: 0,
    fullscreen: false,
    promptHistory: [],
    batchCount: 1,
    loopGeneration: preview.workspace.loopGeneration,
    presets: [],
    customAspectRatios: [],
    theme: "dark",
    fontScale: 1,
    workspaces: [preview.workspace],
    activeWorkspaceId: workspaceId,
    styleTag: preview.currentImage.styleTag ?? "",
    undoStack: [],
    redoStack: [],
    resultDetail: null,
    settingsOpen: false,
    isTestingKey: false,
    isOptimizingPrompt: false,
    customAspectRatioModalOpen: false,
    customSizeModalOpen: false,
    upstreamModalOpen: false,
    upstreamReturnTarget: "app",
    starPromptOpen: false,
    starPromptSource: "auto",
  });
}

export function applyWindowsRightRailPreviewToStore(workspaceId = "preview-workspace") {
  const preview = buildWindowsRightRailPreview(workspaceId);
  applyTheme("light");
  document.documentElement.style.setProperty("--font-scale", "1");

  useStudioStore.setState({
    apiKey: "sk-preview",
    mode: "generate",
    prompt: preview.workspace.prompt,
    negativePrompt: preview.workspace.negativePrompt,
    size: preview.workspace.size,
    quality: preview.workspace.quality,
    outputFormat: preview.workspace.outputFormat,
    seed: preview.workspace.seed,
    background: preview.workspace.background,
    outputCompression: preview.workspace.outputCompression,
    inputFidelity: preview.workspace.inputFidelity,
    imageStyle: preview.workspace.imageStyle,
    moderation: preview.workspace.moderation,
    userIdentifier: "",
    partialImages: preview.workspace.partialImages,
    autoRetryEnabled: true,
    autoRetryCount: DEFAULT_AUTO_RETRY_COUNT,
    kernelRuntimeMode: "auto",
    baseURL: preview.profile.baseURL,
    textModelID: preview.profile.textModelID,
    imageModelID: preview.profile.imageModelID,
    reasoningEffort: preview.profile.reasoningEffort,
    apiMode: preview.profile.apiMode,
    requestPolicy: preview.profile.requestPolicy,
    noPromptRevision: true,
    profiles: [preview.profile],
    activeProfileId: preview.profile.id,
    sources: preview.sources,
    runningJobs: [],
    jobsTotal: 0,
    jobsCompleted: 0,
    progress: null,
    streamPreview: null,
    streamPreviews: {},
    lastLogLine: "",
    errorMessage: null,
    errorRawPath: null,
    isRunning: false,
    lastPayload: null,
    runningJobMeta: {},
    currentImage: preview.currentImage,
    history: preview.history,
    batchResults: [],
    resultGridOpen: false,
    historyRailCollapsed: false,
    historyTimelineOpen: false,
    tool: "pan",
    brushSize: 24,
    brushMode: "paint",
    annotationKind: "rect",
    annotationColor: "#ff4d4d",
    selectedAnnotationId: null,
    maskDataURL: null,
    strokes: [],
    annotations: [],
    compareB: null,
    compareSplit: 0.5,
    toasts: [],
    recentDurations: preview.history.map((item) => item.elapsedSec ?? 0).filter((value) => value > 0),
    viewZoom: 1,
    canvasViewResetTick: 0,
    fullscreen: false,
    promptHistory: [],
    promptTemplates: preview.promptTemplates ?? [],
    batchCount: preview.workspace.batchCount,
    loopGeneration: preview.workspace.loopGeneration,
    presets: preview.presets ?? [],
    customAspectRatios: [],
    theme: "light",
    fontScale: 1,
    workspaces: [preview.workspace],
    activeWorkspaceId: workspaceId,
    styleTag: preview.currentImage.styleTag ?? "",
    undoStack: [],
    redoStack: [],
    resultDetail: null,
    settingsOpen: false,
    isTestingKey: false,
    isOptimizingPrompt: false,
    customAspectRatioModalOpen: false,
    customSizeModalOpen: false,
    upstreamModalOpen: false,
    upstreamReturnTarget: "app",
    starPromptOpen: false,
    starPromptSource: "auto",
  });
}
